# Generated by Django 4.1.5 on 2023-06-03 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mascotas', '0002_alter_producto_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='marca',
            field=models.CharField(default='Sin especificar', max_length=45, verbose_name='Marca'),
        ),
    ]
