# Generated by Django 4.1.5 on 2023-06-03 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mascotas', '0003_producto_marca'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='Categoria',
            new_name='categoria',
        ),
    ]
