# Generated by Django 4.1.5 on 2023-06-03 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mascotas', '0004_rename_categoria_producto_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.IntegerField(default='0', verbose_name='Precio'),
        ),
    ]
