# Generated by Django 4.1.5 on 2023-06-07 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mascotas', '0006_producto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='favorito',
            field=models.BooleanField(default=False),
        ),
    ]
